server:
  port: 8001
spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: prod
---
spring:
  config:
    activate:
      on-profile: dev
server:
  tomcat:
    max-connections: 10001
    threads:
      max: 300